### ISSUE TITLE
ビデオチャット機能

### ISSUE THREAD

**Issue by nyamadori** [ateam-popcorn/reach#6]
- [x] 一対一のチャット (issue #45)
- [ ] 一対多のチャット
  - [x] 会議 (Meeting) のルーティング変更: issue #49 
  - [x] 会議作成ページ　`GET /meetings/new` : issue #46
  - [x] 会議作成アクション　`POST /meetings`: issue #47
  - [x] ~~会議表示ページ (チャット画面)　`GET /meetings/:id`: issue #48~~
  - [x] 一般ユーザが会議に参加する機能 #54
  - [x] ルーム (Room) モデルの作成: issue #52 
  - [x] グループチャットページ作成 `GET /meetings/:id/room`: issue #63
